###
POST http://localhost:4000/api/v1/register
content-type: application/json

{
  "userName": "admin4",
  "email": "admin4@gmail.com",
  "password": "1234567"
}

###
POST http://localhost:4000/api/v1/login
content-type: application/json

{
  "email": "admin4@gmail.com",
  "password": "1234567"
}

###
POST http://localhost:4000/api/v1/refresh
content-type: application/json

###
POST http://localhost:4000/api/v1/logout
content-type: application/json

###
GET http://localhost:4001/api/v1/movies
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzQyMDUwNTcwLCJleHAiOjE3NDIwNTE0NzB9.5be3HbWa-dp5YOPnC74a0DYZ9zCbzqSbXsfnLPIjDGU

###
GET http://localhost:4000/api/v1/movies?genre=action

###
GET http://localhost:4000/api/v1/movies?orderDirection=asc

### 
GET http://localhost:4000/api/v1/movies?genre=suspense&orderDirection=desc

###
POST http://localhost:4000/api/v1/directors
content-type: application/json

{
  "name": "Shonda Lynn Rhimes"
}

###
GET http://localhost:4000/api/v1/episodes/11